---
- name: Installing Webserver Software
  apt: name={{ item }} 
  with_items:
  - apache2

- name: Enabling Proxy module
  apache2_module: name=proxy_http
   
- name: Adding proxy configurtion
  template: src=../files/proxy.conf dest=/etc/apache2/conf-available owner=root group=root mode=0644 
